services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend-node

  backend-node:
    build: ./backend-node
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/chemtools
    depends_on:
      - mongodb
      - backend-python

  backend-python:
    build: ./backend-python
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/chemtools

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: